// Loads every entity file (in dependency order) with plain <script> tags, so it
// works when the page is opened straight from disk (file://).
//
// TO ADD A NEW ENTITY: create entities/<id>.js (copy an existing one) and add its
// file name to the list below, before 'core/phobia-finish.js'.
// Requires lib/three.js, lib/BufferGeometryUtils.js and lib/shaderpatch.js first.
(function () {
  var base = document.currentScript.src.replace(/[^\/]*$/, '');
  var files = [
    'core/registry.js',
    'core/rig.js',
    'core/models-kit.js',
    'core/phobia-kit-a.js',
    'core/phobia-kit-b.js',
    'core/phobia-ai.js',
    'smiler.js',
    'partygoer.js',
    'howler.js',
    'skinstealer.js',
    'chase.js',
    'hound.js',
    'faceling.js',
    'wretch.js',
    'clump.js',
    'deathmoth.js',
    'mannequin.js',
    'haze.js',
    'worm.js',
    'whisperer.js',
    'stature.js',
    'crawler.js',
    'duller.js',
    'troglosidae.js',
    'window.js',
    'beast.js',
    'peripheral.js',
    'puppet.js',
    'weaver.js',
    'coil.js',
    'goodboy.js',
    'murder.js',
    'ninelives.js',
    'revenant.js',
    'porcelain.js',
    'showman.js',
    'jester.js',
    'mourner.js',
    'phlebotomist.js',
    'lure.js',
    'palestag.js',
    'updraft.js',
    'colossus.js',
    'squeeze.js',
    'horizon.js',
    'absence.js',
    'deephand.js',
    'onlooker.js',
    'someone.js',
    'hive.js',
    'umbra.js',
    'reflection.js',
    'examiner.js',
    'flawless.js',
    'arbiter.js',
    'sandman.js',
    'thorn.js',
    'formless.js',
    'dread.js',
    'phantom.js',
    'stranger.js',
    'hourman.js',
    'counter.js',
    'glitch.js',
    'stormcaller.js',
    'frostbitten.js',
    'bleeder.js',
    'bloom.js',
    'librarian.js',
    'overgrowth.js',
    'glutton.js',
    'rootwalker.js',
    'demon.js',
    'shadow.js',
    'supervisor.js',
    'gremlin.js',
    'shade.js',
    'core/phobia-finish.js',
    // bonus packs: mutated / repainted variants of the creatures above
    'core/mutate.js',
    'corruption.js',
    'playground.js'
  ];
  for (var i = 0; i < files.length; i++) document.write('<script src="' + base + files[i] + '"><\/script>');
})();
